export const TIPO_PROPRIEDADE = {
  PROPRIA: 'PROPRIA',
  PARCERIA: 'PARCERIA',
  ARRENDADA: 'ARRENDADA',
  TODAS: 'TODAS'
};

export const SITUACAO_ESTIMATIVA = {
  SOMENTE_ESTIMATIVA: 'SOMENTE_ESTIMATIVA',
  SOMENTE_REESTIMATIVA: 'SOMENTE_REESTIMATIVA',
  AMBOS: 'AMBOS',
  PENDENTES: 'PENDENTES'
};

export const AGRUPAR_POR = {
  CORTE: 'CORTE',
  FAZENDA: 'FAZENDA',
  FAZENDA_E_TALHAO: 'FAZENDA_E_TALHAO',
  TIPO_PROPRIEDADE: 'TIPO_PROPRIEDADE'
};

export const ORDENAR_POR = {
  CORTE: 'CORTE',
  FAZENDA: 'FAZENDA',
  TALHAO: 'TALHAO',
  MAIOR_TONELADA: 'MAIOR_TONELADA',
  MAIOR_VARIACAO: 'MAIOR_VARIACAO'
};

export const MODO_EXIBICAO = {
  RESUMIDO: 'RESUMIDO',
  DETALHADO: 'DETALHADO',
  RESUMIDO_DETALHADO: 'RESUMIDO_DETALHADO'
};

export const COMPARAR_POR = {
  ESTIMATIVA_X_REESTIMATIVA: 'ESTIMATIVA_X_REESTIMATIVA',
  REEST_ANT_X_REEST_ATUAL: 'REEST_ANT_X_REEST_ATUAL'
};

export const TIPO_RELATORIO = {
  POR_CORTE: 'POR_CORTE',
  POR_FAZENDA_TALHAO: 'POR_FAZENDA_TALHAO'
};

export const FORMATO_SAIDA = {
  JSON: 'JSON',
  PDF: 'PDF',
  EXCEL: 'EXCEL'
};
